version: 2.1
orbs:
    heroku: circleci/heroku@1.2.4
workflows:
    deploy:
        jobs:
            - heroku/push-docker-image:
                api-key: $HEROKU_API_KEY
                process-types: $HEROKU_PROCESS_TYPE
