version: 2.1
jobs:
    build:
        docker:
            - image: heroku/default
        steps:
            - setup_remote_docker
            - heroku/install
            - heroku/check-authentication
            - checkout
            - run:
                name: build and push image to heroku registry
                command:
                    HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login
                    HEROKU_API_KEY=${HEROKU_API_KEY} container:push -a ${HEROKU_APP_NAME} ${HEROKU_PROCESS_TYPE}
            - heroku/release-docker-image
orbs:
    heroku: circleci/heroku@1.2.4