version: 2.1
orbs:
    heroku: circleci/heroku@1.2.4
jobs:
    build:
        docker:
            - image: circleci/node:10.23-stretch-browsers-legacy
        steps:
            - checkout
            - run:
                name: Build and push Docker image to Heroku
                command: |
                    sudo curl https://cli-assets.heroku.com/install.sh | sh
                    systemctl start docker
                    HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
                    HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push -a ${HEROKU_APP_NAME} ${HEROKU_PROCESS_TYPE}
                    HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release -a ${HEROKU_APP_NAME} ${HEROKU_PROCESS_TYPE}
